services:
  - type: web
    name: zeroflaw-web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8555
      - key: CODEQL_ENABLED
        value: "true"
      - key: ZAP_ENABLED
        value: "true"
      - key: DEEPSEEK_API_KEY
        sync: false
